### ISSUE TITLE
Add an 'Accessibility Swarm' section

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/accessibility-news-and-you#16]
It would be useful to have a document describing what an Accessibility Swarm is and how to run one.

I understand @greenc05 has a slideshow version introducing an Accessibility Swarm... perhaps that could be a starting point?

Depended on by https://github.com/BBC-News/psammead/issues/103.

**Comment by greenc05** [comment]
This is done

**Comment by ChrisBAshton** [comment]
Fixed in #17
