### ISSUE TITLE
Pa11y Dashboard

### ISSUE THREAD

**Issue by mgifford** [bbc/accessibility-news-and-you#56]
Here https://bbc.github.io/accessibility-news-and-you/accessibility-news-and-product-owners

You mention a "Pa11y Dashboard" and say "This dashboard is to be released early 2017."

Did this happen?  If so can this be updated?

**Comment by greenc05** [comment]
Afraid this didn't happen @mgifford I'm aware the reference needs removing, thank you.

**Comment by mgifford** [comment]
Drat.. That's too bad..  Hopefully someone else will develop it.
